/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as DevDesignSystemRouteImport } from './routes/dev.design-system'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCirclesIndexRouteImport } from './routes/_app/circles/index'
import { Route as AppCelebritiesIndexRouteImport } from './routes/_app/celebrities/index'
import { Route as AppCirclesIdRouteImport } from './routes/_app/circles/$id'
import { Route as AppCelebritiesIdRouteImport } from './routes/_app/celebrities/$id'
import { Route as AppAdminCelebritiesIndexRouteImport } from './routes/_app/admin/celebrities/index'
import { Route as AppAdminCelebritiesNewRouteImport } from './routes/_app/admin/celebrities/new'
import { Route as AppAdminCelebritiesIdRouteImport } from './routes/_app/admin/celebrities/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesIndexRoute = AppCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => AppRoute,
} as any)
const AppCelebritiesIndexRoute = AppCelebritiesIndexRouteImport.update({
  id: '/celebrities/',
  path: '/celebrities/',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesIdRoute = AppCirclesIdRouteImport.update({
  id: '/circles/$id',
  path: '/circles/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCelebritiesIdRoute = AppCelebritiesIdRouteImport.update({
  id: '/celebrities/$id',
  path: '/celebrities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCelebritiesIndexRoute =
  AppAdminCelebritiesIndexRouteImport.update({
    id: '/admin/celebrities/',
    path: '/admin/celebrities/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminCelebritiesNewRoute = AppAdminCelebritiesNewRouteImport.update({
  id: '/admin/celebrities/new',
  path: '/admin/celebrities/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCelebritiesIdRoute = AppAdminCelebritiesIdRouteImport.update({
  id: '/admin/celebrities/$id',
  path: '/admin/celebrities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/celebrities/$id': typeof AppCelebritiesIdRoute
  '/circles/$id': typeof AppCirclesIdRoute
  '/celebrities/': typeof AppCelebritiesIndexRoute
  '/circles/': typeof AppCirclesIndexRoute
  '/admin/celebrities/$id': typeof AppAdminCelebritiesIdRoute
  '/admin/celebrities/new': typeof AppAdminCelebritiesNewRoute
  '/admin/celebrities/': typeof AppAdminCelebritiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/celebrities/$id': typeof AppCelebritiesIdRoute
  '/circles/$id': typeof AppCirclesIdRoute
  '/celebrities': typeof AppCelebritiesIndexRoute
  '/circles': typeof AppCirclesIndexRoute
  '/admin/celebrities/$id': typeof AppAdminCelebritiesIdRoute
  '/admin/celebrities/new': typeof AppAdminCelebritiesNewRoute
  '/admin/celebrities': typeof AppAdminCelebritiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/celebrities/$id': typeof AppCelebritiesIdRoute
  '/_app/circles/$id': typeof AppCirclesIdRoute
  '/_app/celebrities/': typeof AppCelebritiesIndexRoute
  '/_app/circles/': typeof AppCirclesIndexRoute
  '/_app/admin/celebrities/$id': typeof AppAdminCelebritiesIdRoute
  '/_app/admin/celebrities/new': typeof AppAdminCelebritiesNewRoute
  '/_app/admin/celebrities/': typeof AppAdminCelebritiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/dev/design-system'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/celebrities/$id'
    | '/circles/$id'
    | '/celebrities/'
    | '/circles/'
    | '/admin/celebrities/$id'
    | '/admin/celebrities/new'
    | '/admin/celebrities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/dev/design-system'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/celebrities/$id'
    | '/circles/$id'
    | '/celebrities'
    | '/circles'
    | '/admin/celebrities/$id'
    | '/admin/celebrities/new'
    | '/admin/celebrities'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/dev/design-system'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/celebrities/$id'
    | '/_app/circles/$id'
    | '/_app/celebrities/'
    | '/_app/circles/'
    | '/_app/admin/celebrities/$id'
    | '/_app/admin/celebrities/new'
    | '/_app/admin/celebrities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DevDesignSystemRoute: typeof DevDesignSystemRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/': {
      id: '/_app/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AppCirclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/celebrities/': {
      id: '/_app/celebrities/'
      path: '/celebrities'
      fullPath: '/celebrities/'
      preLoaderRoute: typeof AppCelebritiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/$id': {
      id: '/_app/circles/$id'
      path: '/circles/$id'
      fullPath: '/circles/$id'
      preLoaderRoute: typeof AppCirclesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/celebrities/$id': {
      id: '/_app/celebrities/$id'
      path: '/celebrities/$id'
      fullPath: '/celebrities/$id'
      preLoaderRoute: typeof AppCelebritiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/celebrities/': {
      id: '/_app/admin/celebrities/'
      path: '/admin/celebrities'
      fullPath: '/admin/celebrities/'
      preLoaderRoute: typeof AppAdminCelebritiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/celebrities/new': {
      id: '/_app/admin/celebrities/new'
      path: '/admin/celebrities/new'
      fullPath: '/admin/celebrities/new'
      preLoaderRoute: typeof AppAdminCelebritiesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/celebrities/$id': {
      id: '/_app/admin/celebrities/$id'
      path: '/admin/celebrities/$id'
      fullPath: '/admin/celebrities/$id'
      preLoaderRoute: typeof AppAdminCelebritiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCelebritiesIdRoute: typeof AppCelebritiesIdRoute
  AppCirclesIdRoute: typeof AppCirclesIdRoute
  AppCelebritiesIndexRoute: typeof AppCelebritiesIndexRoute
  AppCirclesIndexRoute: typeof AppCirclesIndexRoute
  AppAdminCelebritiesIdRoute: typeof AppAdminCelebritiesIdRoute
  AppAdminCelebritiesNewRoute: typeof AppAdminCelebritiesNewRoute
  AppAdminCelebritiesIndexRoute: typeof AppAdminCelebritiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppCelebritiesIdRoute: AppCelebritiesIdRoute,
  AppCirclesIdRoute: AppCirclesIdRoute,
  AppCelebritiesIndexRoute: AppCelebritiesIndexRoute,
  AppCirclesIndexRoute: AppCirclesIndexRoute,
  AppAdminCelebritiesIdRoute: AppAdminCelebritiesIdRoute,
  AppAdminCelebritiesNewRoute: AppAdminCelebritiesNewRoute,
  AppAdminCelebritiesIndexRoute: AppAdminCelebritiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DevDesignSystemRoute: DevDesignSystemRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
